services:
  - type: web
    name: passa-ou-repassa
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx next start --port $PORT
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
