import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";

const dbUrl = process.env.DATABASE_URL || "file:./dev.db";
const adapter = new PrismaLibSql({
  url: dbUrl,
  authToken: process.env.TURSO_AUTH_TOKEN,
});
const prisma = new PrismaClient({ adapter });

const categoriasChallenge = [
  "Habilidade", "Equilíbrio", "Memória", "Conhecimento", "Coordenação", "Humor",
];

const niveis = ["Fácil", "Médio", "Difícil", "Épico"];
const tempos = ["15 segundos", "30 segundos", "45 segundos", "60 segundos", "90 segundos", "120 segundos"];
const perguntas = [
  { pergunta: "Qual é o maior planeta do sistema solar?", resposta: "Júpiter", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos ossos tem o corpo humano adulto?", resposta: "Entre 206 e 213", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual órgão é responsável por bombear o sangue?", resposta: "Coração", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a velocidade da luz no vácuo?", resposta: "300.000 km/s", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Em qual parte da célula está o DNA?", resposta: "Núcleo", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos elementos químicos existem na tabela periódica?", resposta: "118", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o maior osso do corpo humano?", resposta: "Fêmur", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual gás as plantas absorvem durante a fotossíntese?", resposta: "Gás carbônico (CO2)", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o planeta mais próximo do Sol?", resposta: "Mercúrio", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que mede a escala Richter?", resposta: "Magnitude de terremotos", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o único mamífero capaz de voar?", resposta: "Morcego", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a camada mais externa da Terra?", resposta: "Crosta terrestre", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o símbolo químico do ouro?", resposta: "Au", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos dentes tem um adulto humano?", resposta: "32", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a função dos glóbulos vermelhos?", resposta: "Transportar oxigênio", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o menor planeta do sistema solar?", resposta: "Mercúrio", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem desenvolveu a teoria da relatividade?", resposta: "Albert Einstein", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos cromossomos tem um ser humano?", resposta: "46", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o pH da água pura a 25°C?", resposta: "7", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o maior órgão do corpo humano?", resposta: "Pele", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos litros de sangue o corpo humano tem em média?", resposta: "5 litros", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a fórmula química da água?", resposta: "H2O", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual animal é conhecido como o rei da selva?", resposta: "Leão", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quanto tempo a luz do Sol leva para chegar à Terra?", resposta: "8 minutos", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior animal do mundo?", resposta: "Baleia azul", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Do que são formados os anéis de Saturno?", resposta: "Partículas de gelo e rocha", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos planetas existem no sistema solar?", resposta: "8", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual osso protege o cérebro?", resposta: "Crânio", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual gás é essencial para a respiração humana?", resposta: "Oxigênio (O2)", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas vértebras formam a coluna vertebral?", resposta: "33", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a unidade de medida da frequência?", resposta: "Hertz (Hz)", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual cientista descobriu a penicilina?", resposta: "Alexander Fleming", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a distância aproximada da Terra ao Sol?", resposta: "150 milhões de km", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o animal mais rápido do mundo?", resposta: "Falcão peregrino", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual planeta é conhecido como planeta vermelho?", resposta: "Marte", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos músculos tem o corpo humano?", resposta: "Mais de 600/650", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a temperatura de ebulição da água ao nível do mar?", resposta: "100°C", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa DNA?", resposta: "Ácido desoxirribonucleico", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o segundo maior planeta do sistema solar?", resposta: "Saturno", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual parte do olho é responsável pela cor?", resposta: "Íris", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantas câmaras tem o coração humano?", resposta: "4", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual elemento químico é essencial para a vida?", resposta: "Carbono", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o menor osso do corpo humano?", resposta: "Estribo (no ouvido)", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a energia produzida pelo Sol?", resposta: "Fusão nuclear", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos pares de costelas tem um ser humano?", resposta: "12", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior satélite natural do sistema solar?", resposta: "Ganímedes (lua de Júpiter", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "O que causa o arco-íris?", resposta: "Refração da luz nas gotas de água", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a velocidade do som no ar?", resposta: "340 m/s (ou cerca de 1.224 km/h)", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual ácido está presente no estômago?", resposta: "Ácido clorídrico", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos prótons tem um átomo de hidrogênio?", resposta: "1", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a maior glândula do corpo humano?", resposta: "Fígado", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem descobriu o Brasil?", resposta: "Pedro Álvares Cabral", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Em que ano o Brasil foi descoberto?", resposta: "1500", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem foi o primeiro presidente do Brasil?", resposta: "Deodoro da Fonseca", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano foi proclamada a Independência do Brasil?", resposta: "1822", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem proclamou a Independência do Brasil?", resposta: "Dom Pedro I", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem foi o líder da Revolução Francesa?", resposta: "Maximilien de Robespierre", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano terminou a Segunda Guerra Mundial?", resposta: "1945", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem escreveu a letra do Hino Nacional Brasileiro?", resposta: "Joaquim Osório Duque Estrada", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a capital do Império Inca?", resposta: "Cusco", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Em que ano foi abolida a escravatura no Brasil?", resposta: "1888", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem assinou a Lei Áurea?", resposta: "Princesa Isabel", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do primeiro navegador a circum-navegar o globo?", resposta: "Fernão de Magalhães", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual civilização construiu as pirâmides de Gizé?", resposta: "Egípcia", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem pintou a Mona Lisa?", resposta: "Leonardo da Vinci", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Em que ano o homem pisou na Lua pela primeira vez?", resposta: "1969", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem foi o primeiro homem a pisar na Lua?", resposta: "Neil Armstrong", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual foi a primeira capital do Brasil?", resposta: "Salvador", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual imperador romano construiu o Coliseu?", resposta: "Vespasiano", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quem foi o último imperador do Brasil?", resposta: "Dom Pedro II", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a mais antiga civilização da Mesopotâmia?", resposta: "Suméria", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano ocorreu a Proclamação da República no Brasil?", resposta: "1889", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem foi o líder da Revolução Cubana?", resposta: "Fidel Castro", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual guerra foi travada entre os Estados do Norte e Sul dos EUA?", resposta: "Guerra Civil Americana", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem foi o faraó mais famoso do Egito?", resposta: "Tutancâmon", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da deusa grega da sabedoria?", resposta: "Atena", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano caiu o Muro de Berlim?", resposta: "1989", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem descobriu a América?", resposta: "Cristóvão Colombo", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país foi o primeiro a dar o voto feminino?", resposta: "Nova Zelândia", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual dinastia construiu a Grande Muralha da China?", resposta: "Ming", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantos anos durou a Guerra dos Cem Anos?", resposta: "116 anos", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quem foi o primeiro presidente negro dos EUA?", resposta: "Barack Obama", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Em que ano foi fundada a cidade de Roma?", resposta: "753 a.C.", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual foi a principal causa da Primeira Guerra Mundial?", resposta: "Assassinato de Francisco Ferdinando", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem foi o autor da Declaração de Independência dos EUA?", resposta: "Thomas Jefferson", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o tipo do primeiro navio que trouxe os portugueses ao Brasil?", resposta: "Caravela", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual cidade foi a primeira capital da República brasileira?", resposta: "Rio de Janeiro", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano ocorreu a Revolução Russa?", resposta: "1917", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem comandou a Inconfidência Mineira?", resposta: "Tiradentes", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual país foi colonizado por Portugal na América do Sul?", resposta: "Brasil", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual era o nome do Império que dominou grande parte da Europa medieval?", resposta: "Império Romano", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem foi o autor de Os Lusíadas?", resposta: "Luís de Camões", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual civilização criou a escrita cuneiforme?", resposta: "Suméria", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual povo construiu Machu Picchu?", resposta: "Incas", categoria: "História", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano o Brasil se tornou república?", resposta: "1889", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem foi o líder da independência da Índia?", resposta: "Mahatma Gandhi", categoria: "História", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital da França?", resposta: "Paris", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o maior país do mundo em extensão territorial?", resposta: "Rússia", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o menor país do mundo?", resposta: "Vaticano", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital do Japão?", resposta: "Tóquio", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos continentes existem?", resposta: "6", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o rio mais extenso do mundo?", resposta: "Rio Amazonas", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a maior floresta tropical do mundo?", resposta: "Floresta Amazônica", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o ponto mais alto do Brasil?", resposta: "Pico da Neblina", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital da Austrália?", resposta: "Camberra", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual país tem o maior número de habitantes?", resposta: "Índia", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a montanha mais alta do mundo?", resposta: "Monte Everest", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual oceano separa a América da Europa?", resposta: "Oceano Atlântico", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital da Argentina?", resposta: "Buenos Aires", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos estados tem o Brasil?", resposta: "26", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital do Canadá?", resposta: "Ottawa", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior deserto do mundo?", resposta: "Antártida", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o clima predominante no Brasil?", resposta: "Tropical", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o país mais populoso da África?", resposta: "Nigéria", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital de Portugal?", resposta: "Lisboa", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o maior arquipélago do mundo?", resposta: "Indonésia", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a maior ilha do mundo?", resposta: "Groenlândia", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital da Itália?", resposta: "Roma", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país tem formato de bota?", resposta: "Itália", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país possui o maior litoral do mundo?", resposta: "Canadá", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a capital do Egito?", resposta: "Cairo", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual cordilheira atravessa a América do Sul?", resposta: "Cordilheira dos Andes", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o ponto mais baixo da Terra?", resposta: "Mar Morto", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos fusos horários tem o Brasil?", resposta: "4", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital da Alemanha?", resposta: "Berlim", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país ocupa a maior parte da Península Ibérica?", resposta: "Espanha", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o menor estado do Brasil?", resposta: "Sergipe", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior estado do Brasil em área?", resposta: "Amazonas", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual rio atravessa o deserto do Saara?", resposta: "Rio Nilo", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o país mais extenso da América do Sul?", resposta: "Brasil", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital da Rússia?", resposta: "Moscou", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o segundo maior país do mundo em área?", resposta: "Canadá", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital da China?", resposta: "Pequim", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país é conhecido como a Terra do Sol Nascente?", resposta: "Japão", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital da África do Sul?", resposta: "Pretória", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantos países existem na América do Sul?", resposta: "12", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior lago de água doce do mundo?", resposta: "Lago Baikal na Sibéria (Rússia)", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Em qual continente está localizado o Egito?", resposta: "África", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual oceano é o maior do mundo?", resposta: "Oceano Pacífico", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital do México?", resposta: "Cidade do México", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o principal rio do Brasil?", resposta: "Rio Amazonas", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a capital da Espanha?", resposta: "Madri", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país tem a maior reserva de água doce do mundo?", resposta: "Brasil", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o resultado de 2 + 2?", resposta: "4", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos lados tem um triângulo?", resposta: "3", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual a raiz quadrada de 144?", resposta: "12", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quanto é 7 × 8?", resposta: "56", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos graus tem um ângulo reto?", resposta: "90 graus", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o valor de π (pi) com duas casas decimais?", resposta: "3,14", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o menor número primo?", resposta: "2", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos segundos tem um minuto?", resposta: "60", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "O que é 15% de 200?", resposta: "30", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos zeros tem um milhão?", resposta: "6", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual a fórmula da área de um círculo?", resposta: "π × r²", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Quanto é 2 elevado à décima potência?", resposta: "1024", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do polígono de 8 lados?", resposta: "Octógono", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos lados tem um hexágono?", resposta: "6", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o resultado de 12 × 12?", resposta: "144", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "O que representa o número zero?", resposta: "Nulo ou vazio", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o maior número primo menor que 10?", resposta: "7", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos mililitros tem um litro?", resposta: "1000", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quanto é 3 × 3 × 3?", resposta: "27", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos centímetros tem um metro?", resposta: "100", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o resultado de 9 × 9?", resposta: "81", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quanto é 100 ÷ 4?", resposta: "25", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual a soma dos ângulos internos de um triângulo?", resposta: "180 graus", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos dias tem um ano bissexto?", resposta: "366", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quanto é 99 + 1?", resposta: "100", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o valor de 2³?", resposta: "8", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos números ímpares existem de 1 a 10?", resposta: "5", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o nome do polígono de 5 lados?", resposta: "Pentágono", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quanto é 25 × 4?", resposta: "100", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o resultado de 6 × 7?", resposta: "42", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos lados tem um decágono?", resposta: "10", categoria: "Matemática", nivel: "Médio", pontos: 10 },
  { pergunta: "Qual é a raiz quadrada de 81?", resposta: "9", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quanto é 8 × 7?", resposta: "56", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantas horas tem um dia?", resposta: "24", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual é a probabilidade de sair cara em uma moeda?", resposta: "50%", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos minutos tem uma hora?", resposta: "60", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o valor absoluto de -10?", resposta: "10", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "O que é uma dezena?", resposta: "10 unidades", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quanto é 0 dividido por 5?", resposta: "0", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos números pares existem de 1 a 20?", resposta: "10", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o resultado de 11 × 11?", resposta: "121", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantas arestas tem um cubo?", resposta: "12", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Quanto é 20% de 50?", resposta: "10", categoria: "Matemática", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior número de dois algarismos?", resposta: "99", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantos múltiplos de 3 existem de 1 a 30?", resposta: "10", categoria: "Matemática", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o resultado de 5 × 5 × 5?", resposta: "125", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantas faces tem um cubo?", resposta: "6", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quanto é 13 × 2?", resposta: "26", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual é o menor número de três dígitos?", resposta: "100", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quanto é 1 bilhão em números?", resposta: "1.000.000.000", categoria: "Matemática", nivel: "Fácil", pontos: 10 },
  { pergunta: "Plural de 'cão' é:", resposta: "Cães", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é a letra que inicia o alfabeto?", resposta: "A", categoria: "Português", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantas letras tem o alfabeto português?", resposta: "26", categoria: "Português", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o antônimo de 'bom'?", resposta: "Mau", categoria: "Português", nivel: "Fácil", pontos: 5 },
  { pergunta: "O que é um substantivo?", resposta: "Palavra que nomeia seres", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o plural de 'animal'?", resposta: "Animais", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que é uma sílaba tônica?", resposta: "Sílaba mais forte da palavra", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o aumentativo de 'casa'?", resposta: "Casarão", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Como se classifica a palavra 'amor' quanto ao número de sílabas?", resposta: "Dissílaba", categoria: "Português", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual é o verbo na frase 'Eu corro todos os dias'?", resposta: "Corro", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que é um adjetivo?", resposta: "Palavra que caracteriza o substantivo", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o sinônimo de 'alegre'?", resposta: "Feliz", categoria: "Português", nivel: "Fácil", pontos: 5 },
  { pergunta: "Quantas vogais tem o alfabeto?", resposta: "5", categoria: "Português", nivel: "Fácil", pontos: 5 },
  { pergunta: "O que é uma crase?", resposta: "Fusão da preposição 'a' com o artigo 'a'", categoria: "Português", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o feminino de 'ator'?", resposta: "Atriz", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que é um pronome?", resposta: "Palavra que substitui o substantivo", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a forma correta: 'há muitos anos' ou 'a muitos anos'?", resposta: "Há muitos anos", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa a palavra 'saudade'?", resposta: "Sentimento de falta de alguém", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas letras tem a palavra 'paralelepípedo'?", resposta: "14", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o coletivo de 'abelha'?", resposta: "Enxame", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o plural de 'cidadão'?", resposta: "Cidadãos", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "O que é uma oração?", resposta: "Frase com verbo", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o antônimo de 'claro'?", resposta: "Escuro", categoria: "Português", nivel: "Fácil", pontos: 5 },
  { pergunta: "O que são sinônimos?", resposta: "Palavras com significado semelhante", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o sujeito da frase 'O menino jogou a bola'?", resposta: "O menino", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "O que é uma preposição?", resposta: "Palavra que liga termos", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o aumentativo de 'amigo'?", resposta: "Amigão", categoria: "Português", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas consoantes tem o alfabeto?", resposta: "21", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o feminino de 'poeta'?", resposta: "Poetisa", categoria: "Português", nivel: "Médio", pontos: 20 },
  { pergunta: "O que significa a expressão 'ficar a ver navios'?", resposta: "Frustrar-se ou não conseguir algo", categoria: "Português", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual é o maior país do mundo em população?", resposta: "Índia", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a cor do céu em um dia claro?", resposta: "Azul", categoria: "Cultura Geral", nivel: "Fácil", pontos: 5 },
  { pergunta: "Em que mês é comemorado o Natal?", resposta: "Dezembro", categoria: "Cultura Geral", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual é o símbolo da paz?", resposta: "Pomba branca", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas cores tem o arco-íris?", resposta: "7", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa a sigla ONU?", resposta: "Organização das Nações Unidas", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do atual papa da Igreja Católica?", resposta: "Papa Francisco", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o filme de maior bilheteria da história?", resposta: "Avatar", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantas cordas tem um violão?", resposta: "6", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa a expressão 'CQC'?", resposta: "Custe o Que Custar", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é a moeda oficial do Japão?", resposta: "Iene", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do maior oceanário do mundo?", resposta: "Oceanário de Lisboa", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a data da independência do Brasil?", resposta: "7 de setembro", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o instrumento musical mais vendido no mundo?", resposta: "Violão", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "O que significa a palavra 'gourmet'?", resposta: "Comida refinada ou de alta qualidade", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é a maior rede social do mundo?", resposta: "Facebook", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos dias tem uma semana?", resposta: "7", categoria: "Cultura Geral", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual é a fruta mais consumida no mundo?", resposta: "Banana", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do vírus que causou a pandemia de 2020?", resposta: "Coronavírus (SARS-CoV-2)", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa a sigla SMS?", resposta: "Short Message Service", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o significado da palavra 'amor' em latim?", resposta: "Amor", categoria: "Cultura Geral", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual a bebida mais consumida no mundo depois da água?", resposta: "Chá", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "O que é Bitcoin?", resposta: "Criptomoeda descentralizada", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é a montanha mais alta do Brasil?", resposta: "Pico da Neblina", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome da primeira mulher a voar sozinha sobre o Atlântico?", resposta: "Amelia Earhart", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a capital dos Estados Unidos?", resposta: "Washington D.C.", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos dentes tem um adulto?", resposta: "32", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o prato típico do Brasil?", resposta: "Feijoada", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa 'internet'?", resposta: "Rede mundial de computadores", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o animal símbolo do Brasil?", resposta: "Sabiá-laranjeira", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior estádio de futebol do mundo?", resposta: "Estádio de Wembley", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a cor da bandeira do Brasil?", resposta: "Verde, amarelo, azul e branco", categoria: "Cultura Geral", nivel: "Fácil", pontos: 5 },
  { pergunta: "O que significa a sigla NASA?", resposta: "Administração Nacional da Aeronáutica e Espaço", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos séculos tem um milênio?", resposta: "10", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do criador do Facebook?", resposta: "Mark Zuckerberg", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual país venceu a Copa do Mundo de 2022?", resposta: "Argentina", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos jogadores tem um time de futebol?", resposta: "11", categoria: "Esportes", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o esporte mais praticado no mundo?", resposta: "Futebol", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do maior vencedor da Fórmula 1?", resposta: "Michael Schumacher", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos pontos vale um try no rugby?", resposta: "5", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual país sediou as Olimpíadas de 2016?", resposta: "Brasil", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do jogador com mais gols na história do futebol?", resposta: "Cristiano Ronaldo", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano o Brasil ganhou sua primeira Copa do Mundo?", resposta: "1958", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos sets tem uma partida de vôlei?", resposta: "5", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o esporte praticado na NBA?", resposta: "Basquete", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a altura de uma cesta de basquete?", resposta: "3,05 metros", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantas medalhas de ouro Pelé ganhou em Copas?", resposta: "3", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual país inventou o futebol?", resposta: "Inglaterra", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quem é o maior artilheiro da história das Copas do Mundo?", resposta: "Miroslav Klose", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantas voltas tem a corrida de Fórmula 1 em Mônaco?", resposta: "78", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o esporte que utiliza uma peteca?", resposta: "Badminton", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos jogadores tem um time de basquete?", resposta: "5", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual tenista tem mais títulos de Grand Slam?", resposta: "Novak Djokovic", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que esporte se usa um taco e uma bola pequena?", resposta: "Beisebol", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a distância de uma maratona?", resposta: "42,195 km", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual nadador tem mais medalhas olímpicas?", resposta: "Michael Phelps", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual esporte é conhecido como 'esporte rei'?", resposta: "Futebol", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas casas tem um tabuleiro de xadrez?", resposta: "64", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o time de futebol com mais títulos mundiais?", resposta: "Real Madrid", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Em que ano o Brasil sediou a Copa do Mundo?", resposta: "1950 e 2014", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do estádio do Maracanã?", resposta: "Estádio Jornalista Mário Filho", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantas faltas são necessárias para um jogador ser expulso no basquete?", resposta: "5", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o peso de um disco de atletismo masculino?", resposta: "2 kg", categoria: "Esportes", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantos jogadores tem um time de vôlei?", resposta: "6", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do principal torneio de tênis britânico?", resposta: "Wimbledon", categoria: "Esportes", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual empresa criou o iPhone?", resposta: "Apple", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do primeiro filme de animação da Disney?", resposta: "Branca de Neve", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual série é conhecida como 'A Guerra dos Tronos' em português?", resposta: "Game of Thrones", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do personagem principal de Super Mario?", resposta: "Mario", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o filme de maior bilheteria do cinema brasileiro?", resposta: "Minha Mãe é uma Peça 3", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual banda cantou 'Bohemian Rhapsody'?", resposta: "Queen", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos filmes tem a saga Harry Potter?", resposta: "8", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o jogo mais vendido da história?", resposta: "Minecraft", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual ator interpretou o Coringa em 'O Cavaleiro das Trevas'?", resposta: "Heath Ledger", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual série brasileira é famosa mundialmente?", resposta: "Cidade dos Homens", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do cachorro do Snoopy?", resposta: "Snoopy (ele é o cachorro)", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o console mais vendido da história?", resposta: "PlayStation 2", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem cantou 'Thriller'?", resposta: "Michael Jackson", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual desenho animado tem um garoto chamado Ash?", resposta: "Pokémon", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do super-herói do MCU que tem um escudo?", resposta: "Capitão América", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas temporadas tem a série Friends?", resposta: "10", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do ator que interpretou Jack em Titanic?", resposta: "Leonardo DiCaprio", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme ganhou o Oscar de melhor filme em 2024?", resposta: "Oppenheimer", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do youtuber mais famoso do Brasil?", resposta: "Whindersson Nunes", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual game é um fenômeno mundial de batalha real?", resposta: "Fortnite", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a duração média de um filme?", resposta: "Entre 90 e 120 minutos", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do primeiro filme da Marvel Studios?", resposta: "Homem de Ferro", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual cantora é conhecida como a Rainha do Pop?", resposta: "Madonna", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual desenho tem personagens chamados Tom e Jerry?", resposta: "Tom e Jerry", categoria: "Entretenimento", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o gênero musical do cantor Mick Jagger?", resposta: "Rock", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o personagem mais famoso da Turma da Mônica?", resposta: "Mônica", categoria: "Entretenimento", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual série mostra a história de Walter White?", resposta: "Breaking Bad", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual filme infantil tem um peixe-palhaço?", resposta: "Procurando Nemo", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do primeiro episódio de Os Simpsons?", resposta: "Simpsons Roasting on an Open Fire", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a plataforma de streaming mais famosa?", resposta: "Netflix", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o país de origem do K-pop?", resposta: "Coreia do Sul", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual banda brasileira cantou 'Tempo Perdido'?", resposta: "Legião Urbana", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual atriz interpretou Hermione em Harry Potter?", resposta: "Emma Watson", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos episódios tem a primeira temporada de Stranger Things?", resposta: "8", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual console da Nintendo é portátil?", resposta: "Nintendo Switch", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do alter ego do Batman?", resposta: "Bruce Wayne", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da música mais tocada no Spotify?", resposta: "Blinding Lights (The Weeknd)", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual filme de animação tem um dragão chamado Fúria da Noite?", resposta: "Como Treinar o Seu Dragão", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o pintor famoso por suas obras abstratas?", resposta: "Pablo Picasso", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior prêmio do cinema mundial?", resposta: "Oscar", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série conta a história de uma família chamada Byrde?", resposta: "Ozark", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do chef mais famoso do Brasil?", resposta: "Alex Atala", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o jogo de dança mais famoso dos arcades?", resposta: "Dance Dance Revolution", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual filme brasileiro ganhou o Oscar de melhor filme estrangeiro?", resposta: "O Pagador de Promessas", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual cantor é conhecido como 'Rei do Pop'?", resposta: "Michael Jackson", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da nave em 'Star Wars' pilotada por Han Solo?", resposta: "Millennium Falcon", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o desenho animado mais antigo da Disney?", resposta: "Steamboat Willie", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do principal antagonista de Mario?", resposta: "Bowser", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do elfo em 'O Senhor dos Anéis'?", resposta: "Legolas", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual atriz brasileira é conhecida internacionalmente?", resposta: "Fernanda Montenegro", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do robô em 'Star Wars' que é dourado?", resposta: "C-3PO", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o brinquedo mais vendido do mundo?", resposta: "Lego", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do famoso relógio britânico?", resposta: "Big Ben", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o livro mais vendido do mundo depois da Bíblia?", resposta: "Dom Quixote", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "O que significa a sigla 'UNESCO'?", resposta: "Organização das Nações Unidas para a Educação, Ciência e Cultura", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual é a maior religião do mundo?", resposta: "Cristianismo", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantas línguas existem no mundo?", resposta: "Aproximadamente 7.000", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual país tem a maior economia do mundo?", resposta: "Estados Unidos", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do primeiro satélite artificial?", resposta: "Sputnik 1", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a maior rede de fast food do mundo?", resposta: "McDonald's", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "O que significa a palavra 'liber' em latim?", resposta: "Livro", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a flor símbolo do Brasil?", resposta: "Ipê amarelo", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a maior cordilheira do mundo?", resposta: "Cordilheira dos Andes", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual oceano é o mais profundo?", resposta: "Oceano Pacífico", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital da Suíça?", resposta: "Berna", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a capital da Irlanda?", resposta: "Dublin", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual país tem o maior deserto quente do mundo?", resposta: "Egito (Deserto do Saara)", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital de Cuba?", resposta: "Havana", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior lago do mundo?", resposta: "Mar Cáspio", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantas regiões tem o Brasil?", resposta: "5", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quais países da América do Sul não têm litoral?", resposta: "Paraguai e Bolívia", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a capital do Peru?", resposta: "Lima", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual planeta tem mais luas no sistema solar?", resposta: "Saturno", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o processo de transformação de lagarta em borboleta?", resposta: "Metamorfose", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a função dos pulmões?", resposta: "Realizar a troca gasosa (respiração)", categoria: "Ciências", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o elemento mais abundante na crosta terrestre?", resposta: "Oxigênio", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual animal é conhecido como o 'cavalo-marinho' na mitologia grega?", resposta: "Hipocampo", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a planta carnívora mais conhecida?", resposta: "Vênus-papa-moscas", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual metal é líquido à temperatura ambiente?", resposta: "Mercúrio", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantos cromossomos tem um camundongo?", resposta: "40", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a unidade de medida da corrente elétrica?", resposta: "Ampère (A)", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Como se chama o medo de altura?", resposta: "Acrofobia", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Quem foi a primeira-dama do Brasil conhecida como 'Mãe dos pobres'?", resposta: "Darcy Vargas", categoria: "História", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual é o país com o maior número de ilhas do mundo?", resposta: "Suécia", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do maior peixe do mundo?", resposta: "Tubarão-baleia", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é a fórmula da água oxigenada?", resposta: "H2O2", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do processo de divisão celular?", resposta: "Mitose/Meiose", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual é o planeta mais frio do sistema solar?", resposta: "Urano", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantos séculos tem o período de 2000 anos?", resposta: "20 séculos", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o significado da palavra 'democracia'?", resposta: "Governo do povo", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o pintor do quadro 'O Grito'?", resposta: "Edvard Munch", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o país com a maior expectativa de vida do mundo?", resposta: "Japão", categoria: "Cultura Geral", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual a cidade mais populosa do Brasil?", resposta: "São Paulo", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é a maior cachoeira do mundo?", resposta: "Salto Angel (Venezuela)", categoria: "Geografia", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantos segundos tem uma hora?", resposta: "3600", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual a idade mínima para votar no Brasil?", resposta: "16 anos", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual é o maior aquário do mundo?", resposta: "Aquário da Geórgia (EUA)", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do maior dinossauro já descoberto?", resposta: "Argentinossauro", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Quantos dias tem o mês de fevereiro em ano bissexto?", resposta: "29", categoria: "Matemática", nivel: "Fácil", pontos: 5 },
  { pergunta: "Qual o nome do primeiro computador eletronico operacional?", resposta: "ENIAC", categoria: "Cultura Geral", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual a capital da Polônia?", resposta: "Varsóvia", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual esporte utiliza um cesto e uma bola laranja?", resposta: "Basquete", categoria: "Esportes", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da famosa torre inclinada da Itália?", resposta: "Torre de Pisa", categoria: "Cultura Geral", nivel: "Fácil", pontos: 10 },
  { pergunta: "Quantos estados tem a Região Nordeste do Brasil?", resposta: "9", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome da maior floresta do mundo?", resposta: "Floresta Amazônica", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da montanha mais alta da África?", resposta: "Kilimanjaro", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Quantas vértebras tem a coluna cervical?", resposta: "7", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o primeiro animal a ir ao espaço?", resposta: "Mosca da Fruta (EUA - 1947)", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do primeiro animal a orbitar a terra?", resposta: "Laika", categoria: "Ciências", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o maior vulcão do sistema solar?", resposta: "Monte Olimpo (Marte)", categoria: "Ciências", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual país é o maior produtor de café do mundo?", resposta: "Brasil", categoria: "Geografia", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do maior arquipélago brasileiro?", resposta: "Fernando de Noronha", categoria: "Geografia", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual episódio de Black Mirror é considerado o mais icônico?", resposta: "San Junipero", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome da atriz que interpreta a personagem Daenerys Targaryen em Game of Thrones?", resposta: "Emilia Clarke", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Em qual filme da Marvel o Thanos aparece pela primeira vez?", resposta: "Vingadores: Era de Ultron", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual série detém o recorde de mais prêmios Emmy já ganhos?", resposta: "Game of Thrones", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome do planeta fictício onde se passa Duna?", resposta: "Arrakis", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Quem interpretou o Coringa no filme de 2019?", resposta: "Joaquin Phoenix", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome da nave espacial em Interestelar?", resposta: "Endurance", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual filme não americano venceu o Oscar de Melhor Filme em 2020?", resposta: "Parasita", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Quantos anéis de poder foram criados na trilogia O Senhor dos Anéis?", resposta: "20", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual ator interpretou Wolverine nos filmes X-Men?", resposta: "Hugh Jackman", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual série da Netflix sobre xadrez fez enorme sucesso em 2020?", resposta: "O Gambito da Rainha", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome do personagem que é uma rapoza no filme Zootopia?", resposta: "Nick Wilde", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual filme de Christopher Nolan apresenta o conceito do 'top' que nunca para de girar?", resposta: "A Origem (Inception)", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual banda britânica cantou 'Yellow Submarine'?", resposta: "The Beatles", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual jogo eletrônico de 2018 foi eleito o Jogo do Ano?", resposta: "God of War", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Quais personagens da Disney dizem 'Hakuna Matata'?", resposta: "Timão e Pumba", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome do maior dragão de Daenerys em Game of Thrones?", resposta: "Drogon", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual filme da Pixar se passa no fundo do mar?", resposta: "Procurando Nemo", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Quantos filmes oficiais tem a saga Star Wars?", resposta: "11", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome da robô femea em WALL-E?", resposta: "EVE (EVA)", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual a franquia de filmes mais longa do cinema?", resposta: "Godzilla (Mais de 30 filmes)", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual atriz interpretou Mulher-Maravilha no cinema?", resposta: "Gal Gadot", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual filme brasileiro foi indicado ao Oscar de Melhor Animação em 2020?", resposta: "O Pergaminho Vermelho", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Em que ano foi lançado o primeiro filme do Harry Potter?", resposta: "2001", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome do ator que interpreta Sherlock Holmes na série da BBC?", resposta: "Benedict Cumberbatch", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual cantor é conhecido como 'O Rei' no Brasil?", resposta: "Roberto Carlos", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual filme de terror de 1973 é considerado um clássico sobre possessão?", resposta: "O Exorcista", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual personagem do MCU é conhecido como 'O Deus do Trovão'?", resposta: "Thor", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual ator interpreta Deadpool nos filmes?", resposta: "Ryan Reynolds", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de 1994 é estrelado por Tom Hanks, rendendo a ele o oscar de melhor ator?", resposta: "Forrest Gump", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do reino em Frozen?", resposta: "Arendelle", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o jogo mais famoso da franquia Call of Duty?", resposta: "Call of Duty 4: Modern Warfare", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual personagem da Disney tem um pai chamado Rei Tritão?", resposta: "Ariel", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual ator viveu o personagem Jack Sparrow?", resposta: "Johnny Depp", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série de anime se passa em um mundo onde 80% da população tem superpoderes?", resposta: "My Hero Academia/Boku no Hero", categoria: "Entretenimento", nivel: "Difícil", pontos: 15 },
  { pergunta: "Qual filme tem a famosa frase 'A vida é como uma caixa de chocolates'?", resposta: "Forrest Gump", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual desenho animado tem um garoto chamado Finn e um cachorro chamado Jake?", resposta: "Hora de Aventura", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do videogame mais vendido do console Nintendo Switch?", resposta: "Mario Kart 8 Deluxe", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do ator que interpreta Iron Man nos filmes da Marvel?", resposta: "Robert Downey Jr.", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de 2018 foi o primeiro filme de super-herói a se indicado ao o Oscar de Melhor Filme?", resposta: "Pantera Negra", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do dragão de soluço no filme Como Treinar o Seu Dragão?", resposta: "Banguela", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da casa mais leal e corajosa do Harry Potter?", resposta: "Grifinória", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Em que ano foi ao ar o primeiro episódio de Friends?", resposta: "1994", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual cantora ficou conhecida como 'Princesa do Pop' nos anos 2000?", resposta: "Britney Spears", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da banda de rock formada por Brian May, Freddie Mercury, Roger Taylor e John Deacon?", resposta: "Queen", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série de TV mostra um professor de química que se torna fabricante de metanfetamina?", resposta: "Breaking Bad", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do robô em Star Wars de cor laranja e branco?", resposta: "BB-8", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de 1985 estrelou Michael J. Fox viajando no tempo?", resposta: "De Volta para o Futuro", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual atriz interpretou Katniss Everdeen nos filmes Jogos Vorazes?", resposta: "Jennifer Lawrence", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do personagem vivido por Brad Pitt em Clube da Luta?", resposta: "Tyler Durden", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual banda britânica lançou o álbum 'The Dark Side of the Moon'?", resposta: "Pink Floyd", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual filme de animação da Disney tem uma personagem chamada Elsa?", resposta: "Frozen", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do elenco principal da série 'Os Simpsons'?", resposta: "Homer, Marge, Bart, Lisa, Maggie", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de ficção científica estrelou Keanu Reeves como Neo?", resposta: "Matrix", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série de anime tem um garoto de sobrenome Uzumaki?", resposta: "Naruto", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de terror japonês foi refilmado nos EUA como 'O Chamado'?", resposta: "Ringu", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual jogo eletrônico apresenta um encanador que salva uma princesa?", resposta: "Super Mario Bros.", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual a série mais longa da TV americana em número de episódios?", resposta: "Os Simpsons", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual ator interpretou o personagem Walter White em Breaking Bad?", resposta: "Bryan Cranston", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do primeiro episódio de The Twilight Zone?", resposta: "Where Is Everybody? (Onde está todo mundo?)", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual o nome do jogo do dinossauro que aparece no Google Chrome offline?", resposta: "T-Rex Runner", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do mestre Jedi que treinou Obi-Wan Kenobi?", resposta: "Qui-Gon Jinn", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual cantor famoso morreu em 2009 e é conhecido como 'Rei do Pop'?", resposta: "Michael Jackson", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série brasileira da Globo mostrava aventuras em um sítio com seres míticos?", resposta: "Sítio do Picapau Amarelo", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual atriz interpretou a personagem Eleven em Stranger Things?", resposta: "Millie Bobby Brown", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual banda irlandesa cantou 'With or Without You'?", resposta: "U2", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do reino encantado em Alice no País das Maravilhas?", resposta: "País das Maravilhas", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual jogo eletrônico de 2020 venceu o Game of the Year?", resposta: "The Last of Us Part II", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome da espada lendária do Rei Arthur?", resposta: "Excalibur", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série de TV é baseada nos livros de George R.R. Martin?", resposta: "Game of Thrones", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de 2023 foi a maior bilheteria do ano?", resposta: "Barbie", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual ator interpretou o personagem Shrek nos filmes?", resposta: "Mike Myers", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome da canção de abertura de Friends?", resposta: "I'll Be There for You (Rembrandts)", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual personagem da Disney é conhecido por ter as orelhas grandes e voar?", resposta: "Dumbo", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual empresa criou o jogo Fortnite?", resposta: "Epic Games", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do antagonista principal de Stranger Things?", resposta: "Vecna", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual filme mostra a história de um menino que vê mortos?", resposta: "O Sexto Sentido", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do famoso festival de música realizado em Nevada, EUA?", resposta: "Burning Man", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual ator interpretou o Pinguim no filme Batman de 2022?", resposta: "Colin Farrell", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual série de anime fala sobre piratas?", resposta: "One Piece", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do filme de 1993 que se passa em uma ilha com animais pre-históricos?", resposta: "Jurassic Park: O Parque dos Dinossauros", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do ator que interpreta o Doutor Estranho?", resposta: "Benedict Cumberbatch", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual banda brasileira cantou 'Epitáfio'?", resposta: "Titãs", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual desenho animado da Cartoon Network mostra um garoto chamado Gumball?", resposta: "O Incrível Mundo de Gumball", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual filme de 1997 foi o maior sucesso de bilheteria até 2010?", resposta: "Titanic", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do personagem vivido por Robin Williams em 'Aladdin'?", resposta: "Gênio", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série da HBO sobre zumbis é baseada em uma série de quadrinhos?", resposta: "The Walking Dead", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do ator que interpretou o Palhaço Pennywise em IT: A Coisa (2017)?", resposta: "Bill Skarsgård", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual jogo de 2017 popularizou o estilo battle royale?", resposta: "PlayerUnknown's Battlegrounds (PUBG)", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual filme de 1977 deu início à franquia Star Wars?", resposta: "Star Wars: Episódio IV - Uma Nova Esperança", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do super-herói que tem um uniforme vermelho e azul e lança teias?", resposta: "Homem-Aranha", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual cantor brasileiro ficou conhecido como 'Rei do Brega'?", resposta: "Reginaldo Rossi", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do podcast mais famoso do Brasil?", resposta: "Podpah", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual atriz interpretou a Mulher-Gato em 'Batman Returns' (1992)?", resposta: "Michelle Pfeiffer", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do personagem mais velho do núcleo clássico da Turma da Mônica?", resposta: "Zé Luis", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual filme infantil tem um personagem chamado Relâmpago McQueen?", resposta: "Carros", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do ator que interpreta o personagem John Wick?", resposta: "Keanu Reeves", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual game da Rockstar se passa em Los Santos?", resposta: "Grand Theft Auto V", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do famoso violinista brasileiro, compositor de Maktub?", resposta: "Marcus Viana", categoria: "Entretenimento", nivel: "Épico", pontos: 50 },
  { pergunta: "Qual série de TV americana é conhecida pela frase 'How you doin'?'?", resposta: "Friends", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do personagem principal de The Witcher na Netflix?", resposta: "Geralt de Rívia", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual banda de rock dos anos 70 tinha um vocalista chamado Freddie Mercury?", resposta: "Queen", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do filme que apresentou o personagem Pantera Negra no MCU?", resposta: "Capitão América: Guerra Civil", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual desenho animado ensina ciência com um garoto chamado Jimmy?", resposta: "Jimmy Nêutron", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual jogo de celular se tornou febre mundial com pássaros e porcos?", resposta: "Angry Birds", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome da princesa da Disney que vive em uma torre e tem um camaleão?", resposta: "Rapunzel (Enrolados)", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série de TV americana se passa em um hospital chamado 'Seattle Grace'?", resposta: "Grey's Anatomy", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o modelo robótico do personagem de Arnold Schwarzenegger em 'O Exterminador do Futuro'?", resposta: "T-800", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual o nome do álbum/disco mais vendido de todos os tempos?", resposta: "Thriller (Michael Jackson)", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual filme de 2019 teve a maior bilheteria do ano?", resposta: "Vingadores: Ultimato", categoria: "Entretenimento", nivel: "Médio", pontos: 20 },
  { pergunta: "Qual o nome do vampiro mais famoso do cinema?", resposta: "Drácula", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual série da Netflix mostra um grupo de crianças nos anos 80 com poderes?", resposta: "Stranger Things", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual o nome do personagem de Tom Hanks em 'Náufrago'?", resposta: "Chuck Noland", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual jogo eletrônico da Mojang é feito de blocos?", resposta: "Minecraft", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
  { pergunta: "Qual atriz interpretou a Mulher-Gato em 'O Batman' (2022)?", resposta: "Zoë Kravitz", categoria: "Entretenimento", nivel: "Difícil", pontos: 30 },
  { pergunta: "Qual filme de 2008 deu início ao Universo Cinematográfico da Marvel?", resposta: "Homem de Ferro", categoria: "Entretenimento", nivel: "Fácil", pontos: 10 },
];

const provas = [
  { nome: "Boca do Palhaço", descricao: "Acertar bolas dentro da boca do palhaço.", instrucao: "Cada participante terá 3 bolas para acertar na boca do palhaço a uma distância de 3 metros." },
  { nome: "Dança da Cadeira", descricao: "Dançar ao redor das cadeiras e sentar quando a música parar.", instrucao: "Ao som da música, os participantes dançam ao redor das cadeiras. Quando a música parar, todos devem sentar. Quem ficar de fora é eliminado." },
  { nome: "Prova do Balão", descricao: "Estourar balões sentando em cima.", instrucao: "Cada participante deve estourar o máximo de balões possível sentando em cima deles dentro do tempo limite." },
  { nome: "Torre de Copos", descricao: "Empilhar copos plásticos formando uma torre.", instrucao: "Com 20 copos plásticos, monte a torre mais alta possível sem deixar cair." },
  { nome: "Mímica Musical", descricao: "Fazer mímicas de cantores ou músicas.", instrucao: "O participante sorteia uma música ou cantor e deve fazer mímica para o time adivinhar. Não pode falar ou emitir sons." },
  { nome: "Cabo de Guerra", descricao: "Puxar a equipe adversária pela corda.", instrucao: "Duas equipes puxam a corda em direções opostas. A equipe que ultrapassar a marcação vence." },
  { nome: "Corrida do Sapo", descricao: "Pular como sapo até a linha de chegada.", instrucao: "Os participantes devem se agachar e pular como sapo até a linha de chegada. O primeiro a chegar vence." },
  { nome: "Encaixe Perfeito", descricao: "Encaixar formas geométricas no lugar certo.", instrucao: "Com blocos de formas variadas, encaixe cada um no seu respectivo lugar no menor tempo possível." },
  { nome: "Prova do Espelho", descricao: "Repetir os movimentos do companheiro.", instrucao: "Dupla: um faz movimentos e o outro deve repetir exatamente como se fosse um espelho." },
  { nome: "Estoura Balão", descricao: "Estourar balões com os pés.", instrucao: "Balões são espalhados pelo chão. Os participantes devem estourar o máximo possível usando apenas os pés." },
  { nome: "Gincana da Memória", descricao: "Memorizar objetos e responder perguntas.", instrucao: "Mostra-se uma bandeja com 15 objetos por 30 segundos. Depois, os participantes devem listar quantos lembrarem." },
  { nome: "Prova da Farinha", descricao: "Encontrar objetos escondidos na farinha.", instrucao: "Objetos pequenos são escondidos em uma bacia com farinha. Os participantes devem encontrá-los usando apenas a boca." },
  { nome: "Corrida do Ovo", descricao: "Correr com um ovo na colher sem deixar cair.", instrucao: "Cada participante segura uma colher com um ovo e precisa percorrer o trajeto sem deixar o ovo cair." },
  { nome: "Prova do Limão", descricao: "Empurrar um limão com o nariz até a meta.", instrucao: "Os participantes devem empurrar um limão usando apenas o nariz até a linha de chegada." },
  { nome: "Dança Imitando", descricao: "Imitar a coreografia do dançarino na tela.", instrucao: "Uma coreografia é exibida na tela. Os participantes devem imitar os passos corretamente." },
  { nome: "Prova da Bexiga d'Água", descricao: "Jogar bexigas d'água sem estourar.", instrucao: "Duplas se posicionam frente a frente e jogam bexigas d'água uma para a outra, dando um passo para trás a cada pegada." },
  { nome: "Jogo dos 7 Erros Humano", descricao: "Identificar diferenças em uma cena ao vivo.", instrucao: "Uma cena é montada com participantes. Depois de 30 segundos, algo é alterado. A equipe deve identificar o que mudou." },
  { nome: "Prova do Elástico", descricao: "Passar por dentro de um elástico sem encostar.", instrucao: "Duas pessoas seguram um elástico. Os participantes devem passar por dentro sem encostar, com o elástico descendo a cada rodada." },
  { nome: "Corrida do Saco", descricao: "Pular dentro de um saco até a linha de chegada.", instrucao: "Cada participante entra em um saco e precisa pular até a linha de chegada. O primeiro a chegar vence." },
  { nome: "Prova do Bigode", descricao: "Desenhar bigode no colega vendado.", instrucao: "Um participante é vendado e precisa desenhar um bigode no rosto do colega seguindo instruções da plateia." },
  { nome: "Desafio das Cores", descricao: "Falar a cor da palavra, não o texto escrito.", instrucao: "Palavras de cores são escritas em cores diferentes. O participante deve falar a cor da tinta, não a palavra lida." },
  { nome: "Prova do Abacaxi", descricao: "Descascar um abacaxi no menor tempo.", instrucao: "Cada participante recebe um abacaxi e deve descascá-lo completamente no menor tempo possível." },
  { nome: "Telefone Sem Fio", descricao: "Passar uma mensagem sussurrando de ouvido a ouvido.", instrucao: "Uma mensagem é sussurrada para o primeiro participante, que repete para o próximo, e assim por diante. O último deve dizer a mensagem em voz alta." },
  { nome: "Prova do Lábio", descricao: "Ler lábios do companheiro.", instrucao: "Um participante fala algo sem som, apenas mexendo os lábios. O outro deve adivinhar o que foi dito." },
  { nome: "Corrida de Três Pernas", descricao: "Dupla com pernas amarradas correndo.", instrucao: "Duas pessoas têm uma perna amarrada à outra e precisam correr juntas até a linha de chegada." },
  { nome: "Prova da Laranja", descricao: "Passar a laranja de pescoço a pescoço.", instrucao: "A laranja deve ser passada de um participante para outro usando apenas o pescoço, sem usar as mãos." },
  { nome: "Desafio do Bambolê", descricao: "Passar o bambolê pelo corpo sem usar as mãos.", instrucao: "O bambolê deve passar da cabeça aos pés e vice-versa sem usar as mãos, apenas com movimentos do corpo." },
  { nome: "Prova do Dedo", descricao: "Equilibrar uma vara no dedo.", instrucao: "Uma vara longa deve ser equilibrada na palma da mão ou dedo pelo maior tempo possível." },
  { nome: "Quiz Rápido", descricao: "Responder perguntas de conhecimento geral.", instrucao: "Perguntas de diversas áreas do conhecimento são feitas e o participante tem 10 segundos para responder cada uma." },
  { nome: "Prova do Globo", descricao: "Equilibrar um globo terrestre na cabeça.", instrucao: "Os participantes devem equilibrar um globo ou bola grande na cabeça enquanto andam por um trajeto." },
  { nome: "Dança da Laranja", descricao: "Dançar com uma laranja entre as testas.", instrucao: "Duplas dançam com uma laranja pressionada entre suas testas sem deixar cair." },
  { nome: "Prova da Corda", descricao: "Pular corda sem errar.", instrucao: "Cada participante deve pular corda sem errar. Ganha quem pular mais vezes consecutivas." },
  { nome: "Mestre Cuca", descricao: "Preparar um sanduíche vendado.", instrucao: "Vendado, o participante deve preparar um sanduíche com os ingredientes disponíveis. O mais completo e bem-feito vence." },
  { nome: "Prova do Sapato", descricao: "Encontrar e calçar os sapatos vendado.", instrucao: "Os sapatos de todos são misturados. Vendado, cada participante deve encontrar e calçar seus próprios sapatos." },
  { nome: "Estátua", descricao: "Congelar em uma posição quando a música parar.", instrucao: "Os participantes dançam livremente. Quando a música para, todos congelam. Quem se mexer é eliminado." },
  { nome: "Prova do Jornal", descricao: "Dançar em cima de um jornal dobrando-o.", instrucao: "Duplas dançam em cima de um jornal aberto. A cada rodada o jornal é dobrado ao meio. Quem pisar fora é eliminado." },
  { nome: "Corrida do Carrinho", descricao: "Um participante empurra o outro de carrinho.", instrucao: "Um segura as pernas do outro que anda com as mãos. A dupla precisa percorrer o trajeto." },
  { nome: "Prova do Canudo", descricao: "Passar bolinhas de papel com canudo.", instrucao: "Cada participante recebe um canudo e deve sugar bolinhas de papel e transportá-las até um recipiente." },
  { nome: "Desafio do Nó", descricao: "Desatar nós em uma corda.", instrucao: "Uma corda com vários nós apertados deve ser desatada completamente no menor tempo possível." },
  { nome: "Prova do Chinês", descricao: "Falar frutas em ordem alfabética.", instrucao: "Os participantes devem dizer nomes de frutas em ordem alfabética sem repetir e sem demorar mais de 3 segundos." },
  { nome: "Prova do Refrigerante", descricao: "Beber refrigerante com canudo curly.", instrucao: "Cada participante deve beber uma lata de refrigerante usando um canudo curly (ondulado) no menor tempo possível." },
  { nome: "Dança do Carrinho", descricao: "Dançar imitando um carrinho de compras.", instrucao: "Coreografia engraçada imitando um carrinho de compras desgovernado deve ser executada." },
  { nome: "Prova da Bolha", descricao: "Fazer a maior bolha de chiclete.", instrucao: "Cada participante recebe chicletes e deve fazer a maior bolha possível. A maior bolha vence." },
  { nome: "Gol Olímpico", descricao: "Fazer gol de cabeça no gol de handebol.", instrucao: "De uma distância determinada, o participante deve fazer gol de cabeça. Cada acerto vale um ponto." },
  { nome: "Prova da Colher", descricao: "Equilibrar colher no nariz.", instrucao: "Uma colher deve ser equilibrada na ponta do nariz pelo maior tempo possível." },
  { nome: "Desafio do Desenho", descricao: "Desenhar algo com os olhos vendados.", instrucao: "Vendado, o participante deve desenhar algo solicitado pela plateia. O desenho mais parecido vence." },
  { nome: "Prova do Dicionário", descricao: "Explicar palavras sem dizer sinônimos.", instrucao: "Uma palavra sorteada deve ser explicada para o time sem usar sinônimos ou palavras da mesma família." },
  { nome: "Corrida do Desentortar", descricao: "Desentortar palitos de sorvete molhados.", instrucao: "Palitos de sorvete foram molhados e entortados. Os participantes devem desentortá-los no menor tempo." },
  { nome: "Prova da Garrafa", descricao: "Virar garrafa pet com água e pousá-la.", instrucao: "Jogar a garrafa pet com um pouco de água para cima e fazê-la pousar em pé no chão." },
  { nome: "Prova da Massinha", descricao: "Modelar um objeto com massinha no escuro.", instrucao: "Com as luzes apagadas, os participantes devem modelar um objeto específico usando massinha de modelar." },
  { nome: "Boliche Maluco", descricao: "Derrubar pinos com uma bola diferente.", instrucao: "Usando uma bola de futebol americano ou bola irregular, derrubar o máximo de pinos possível." },
  { nome: "Prova do Palhaço", descricao: "Fazer o maior número de caretas.", instrucao: "Em 30 segundos, fazer o maior número possível de caretas diferentes. A plateia julga a melhor." },
  { nome: "Desafio da Pirâmide", descricao: "Formar uma pirâmie humana.", instrucao: "A equipe deve formar uma pirâmide humana e manter por 10 segundos." },
  { nome: "Prova do Fantasma", descricao: "Envolver o colega em papel higiênico.", instrucao: "Um participante deve enrolar completamente o colega em papel higiênico, formando uma múmia, no menor tempo." },
  { nome: "Corrida do Gole", descricao: "Beber água e assobiar.", instrucao: "Cada participante deve beber um copo de água e assobiar em seguida. Quem assobiar primeiro vence." },
  { nome: "Prova da Cadeira", descricao: "Girar ao redor da cadeira e sentar.", instrucao: "O participante gira 10 vezes ao redor da cadeira e tenta sentar. Quem sentar mais reto vence." },
  { nome: "Desafio da Meia", descricao: "Tirar a meia do outro usando apenas os pés.", instrucao: "Duplas sentadas frente a frente tentam tirar a meia do outro usando apenas os pés." },
  { nome: "Prova do Pijama", descricao: "Vestir pijama por cima da roupa.", instrucao: "Cada participante deve vestir um pijama completo por cima da roupa no menor tempo possível." },
  { nome: "Prova do Suco", descricao: "Fazer um suco e servir vendado.", instrucao: "Vendado, o participante deve preparar um copo de suco a partir de frutas e servir sem derramar." },
  { nome: "Dança do Ventre", descricao: "Dançar com moedas na barriga sem deixar cair.", instrucao: "Moedas são colocadas na barriga do participante que deve dançar sem deixar nenhuma cair no chão." },
  { nome: "Prova do Travesseiro", descricao: "Batalha de travesseiro em cima de um banco.", instrucao: "Duas pessoas se enfrentam em cima de um banco usando travesseiros. Quem cair primeiro perde." },
  { nome: "Corrida do Pneuzinho", descricao: "Rolar pneu até a linha de chegada.", instrucao: "Cada participante deve rolar um pneu por um trajeto sinuoso até a linha de chegada." },
  { nome: "Prova do Pirata", descricao: "Andar em linha reta com tapa-olho.", instrucao: "Com um tapa-olho, o participante deve andar em linha reta sobre uma fita no chão sem sair dela." },
  { nome: "Desafio do Ritmo", descricao: "Repetir sequência de palmas.", instrucao: "Uma sequência de palmas é executada e o participante deve repeti-la exatamente igual." },
  { nome: "Prova da Voz", descricao: "Reconhecer a voz do colega.", instrucao: "Vendado, o participante deve reconhecer a voz de cada membro da equipe falando uma frase." },
  { nome: "Prova do Dado", descricao: "Falar um tema conforme o número do dado.", instrucao: "Joga-se um dado. Cada número corresponde a um tema sobre o qual o participante deve falar por 30 segundos sem parar." },
  { nome: "Prova do Cabelo", descricao: "Fazer um penteado maluco no colega.", instrucao: "Com grampos, elásticos e gel, fazer o penteado mais criativo possível no colega." },
  { nome: "Corrida do Vento", descricao: "Soprar bolinha de pingue-pongue até a meta.", instrucao: "Uma bolinha de pingue-pongue deve ser soprada por um labirinto até a saída." },
  { nome: "Prova do Siri", descricao: "Andar como siri (de costas).", instrucao: "Os participantes devem percorrer o trajeto andando de costas como um siri. O primeiro a chegar vence." },
  { nome: "Desafio da Escultura", descricao: "Virar estátua imitando uma escultura famosa.", instrucao: "Uma imagem de escultura famosa é mostrada. O participante deve imitar a pose exatamente." },
  { nome: "Prova do Chapéu", descricao: "Acertar chapéu na cabeça do colega.", instrucao: "De uma distância determinada, o participante deve arremessar chapéus para acertar na cabeça do colega." },
  { nome: "Prova da Gaita", descricao: "Tocar uma música na gaita de boca.", instrucao: "Cada participante deve tentar tocar uma música conhecida na gaita de boca. A plateia julga." },
  { nome: "Corrida do Saco de Batata", descricao: "Correr com um saco de batata nas costas.", instrucao: "Cada participante carrega um saco de batata nas costas e precisa correr até a linha de chegada." },
  { nome: "Prova do Ioiô", descricao: "Fazer manobras com ioiô.", instrucao: "Cada participante deve executar o maior número de manobras diferentes com um ioiô." },
  { nome: "Prova do Objeto Escondido", descricao: "Encontrar objeto escondido na sala.", instrucao: "Um objeto é escondido na sala enquanto o participante espera fora. Ele deve encontrá-lo no menor tempo." },
  { nome: "Prova do Riso", descricao: "Fazer o outro rir primeiro.", instrucao: "Duplas frente a frente. Um tenta fazer o outro rir sem tocar. Quem rir primeiro perde." },
  { nome: "Desafio do Tênis", descricao: "Amarrar o tênis com uma mão só.", instrucao: "Com uma das mãos amarrada para trás, o participante deve amarrar o próprio tênis." },
  { nome: "Prova do Patinho", descricao: "Andar agachado feito pato.", instrucao: "Os participantes devem andar agachados imitando patos até a linha de chegada." },
  { nome: "Prova do Ventríloquo", descricao: "Falar sem mexer os lábios.", instrucao: "O participante deve falar uma frase sem mexer os lábios para o time adivinhar o que foi dito." },
  { nome: "Corrida do Balão nos Pés", descricao: "Estourar balão amarrado no pé do outro.", instrucao: "Cada participante tem um balão amarrado no tornozelo. Devem estourar o balão dos outros protegendo o seu." },
  { nome: "Prova da Banana", descricao: "Comer banana sem usar as mãos.", instrucao: "Uma banana pendurada em um barbante deve ser comida sem usar as mãos." },
  { nome: "Prova do Cotovelo", descricao: "Tocar o nariz com o cotovelo.", instrucao: "O participante precisa conseguir tocar a ponta do nariz com o cotovelo do mesmo braço." },
  { nome: "Desafio do Palito", descricao: "Tirar palitos de uma pilha sem derrubar.", instrucao: "Uma pilha de palitos é montada. Cada participante tira um palito por vez sem derrubar os outros." },
  { nome: "Prova do Pintor", descricao: "Pintar um quadro vendado.", instrucao: "Vendado, o participante deve pintar uma paisagem simples em uma tela. A melhor pintura vence." },
  { nome: "Prova do Hambúrguer", descricao: "Montar um hambúrguer gigante.", instrucao: "Com diversos ingredientes disponíveis, montar o hambúrguer mais alto possível sem derrubar." },
  { nome: "Corrida do Gato", descricao: "Andar de quatro como gato.", instrucao: "Os participantes devem percorrer o trajeto andando de quatro como gatos. O mais rápido vence." },
  { nome: "Prova do Pé de Cabra", descricao: "Desvirar uma bota com os pés.", instrucao: "Uma bota está virada. O participante deve desvirá-la usando apenas os pés." },
  { nome: "Prova da Perna de Pau", descricao: "Andar de perna de pau.", instrucao: "Cada participante deve percorrer um trajeto curto usando pernas de pau sem cair." },
  { nome: "Prova dos Palitos Chineses", descricao: "Pegar objetos com hashis.", instrucao: "Usando hashis (palitos chineses), pegar o maior número de objetos pequenos e transferi-los para outro recipiente." },
  { nome: "Desafio do Gelo", descricao: "Derreter cubo de gelo na mão.", instrucao: "Cada participante recebe um cubo de gelo e deve derretê-lo usando apenas o calor das mãos." },
  { nome: "Prova da Bolinha de Gude", descricao: "Soprar bolinha de gude até o buraco.", instrucao: "Com um canudo, soprar a bolinha de gude até fazê-la cair no buraco no menor número de sopros." },
  { nome: "Prova do Malabarista", descricao: "Fazer malabarismo com 3 bolas.", instrucao: "Cada participante deve fazer malabarismo com 3 bolas pelo maior tempo possível sem derrubar." },
  { nome: "Prova do Mímico de Animais", descricao: "Imitar animal para o time adivinhar.", instrucao: "Sorteia-se um animal e o participante deve imitá-lo com sons e movimentos para o time adivinhar." },
  { nome: "Dança do Robô", descricao: "Dançar como robô.", instrucao: "Coreografia robótica deve ser executada. A plateia julga o robô mais convincente." },
  { nome: "Prova do Grito", descricao: "Gritar sem desafinar.", instrucao: "Cada participante deve dar um grito agudo mantendo a nota por pelo menos 10 segundos sem desafinar." },
  { nome: "Prova do Chocolate", descricao: "Comer chocolate com garfo e faca.", instrucao: "Usando garfo e faca, comer uma barra de chocolate no menor tempo possível." },
  { nome: "Prova do Cigarro", descricao: "Apagar velas com sopro forte.", instrucao: "Uma fileira de 10 velas deve ser apagada com um único sopro. Quantas mais apagar, melhor." },
  { nome: "Desafio do Dominó", descricao: "Montar fileira de dominós e derrubar.", instrucao: "Com 30 peças de dominó, montar uma fileira e derrubar todas de uma só vez." },
  { nome: "Prova da Fruta na Corda", descricao: "Comer maçã pendurada na corda.", instrucao: "Maçãs são penduradas em cordas. Os participantes devem comê-las sem usar as mãos." },
  { nome: "Prova do Pé na Lata", descricao: "Andar com latas nos pés.", instrucao: "Latas são amarradas nos pés como pernas de pau improvisadas. Percorrer o trajeto sem cair." },
];

async function main() {
  console.log("Iniciando seed...");

  const existingAdmin = await prisma.userAdmin.findFirst();
  if (!existingAdmin) {
    const bcrypt = await import("bcryptjs");
    const passwordHash = await bcrypt.hash("admin123", 10);
    await prisma.userAdmin.create({
      data: {
        nome: "Administrador",
        email: "admin@jogo.com",
        passwordHash,
      },
    });
    console.log("Admin padrão criado: admin@jogo.com / admin123");
  } else {
    console.log("Admin já existe. Pulando...");
  }

  const existingQuestions = await prisma.question.count();
  if (existingQuestions === 0) {
    for (const q of perguntas) {
      await prisma.question.create({ data: q });
    }
    console.log(`${perguntas.length} perguntas criadas!`);
  } else {
    await prisma.question.deleteMany();
    for (const q of perguntas) {
      await prisma.question.create({ data: q });
    }
    console.log(`${perguntas.length} perguntas recriadas (havia ${existingQuestions})!`);
  }

  const existingCount = await prisma.challenge.count();
  if (existingCount === 0) {
    for (const prova of provas) {
      const cat = categoriasChallenge[Math.floor(Math.random() * categoriasChallenge.length)];
      const nivel = niveis[Math.floor(Math.random() * niveis.length)];
      const tempo = tempos[Math.floor(Math.random() * tempos.length)];
      await prisma.challenge.create({
        data: {
          nome: prova.nome,
          descricao: prova.descricao,
          instrucao: prova.instrucao,
          categoria: cat,
          nivel,
          tempo,
        },
      });
    }
    console.log(`${provas.length} provas criadas!`);
  } else {
    console.log(`${existingCount} provas já existem. Pulando...`);
  }

  const existingTeams = await prisma.teamConfig.count();
  if (existingTeams === 0) {
    await prisma.teamConfig.createMany({
      data: [
        { nome: "Azul", cor: "#4A90D9", ordem: 0 },
        { nome: "Vermelho", cor: "#E74C3C", ordem: 1 },
      ],
    });
    console.log("Times padrão criados!");
  } else {
    console.log(`${existingTeams} times já existem. Pulando...`);
  }

  const existingMagic = await prisma.systemConfig.findUnique({ where: { key: "magic_word" } });
  if (!existingMagic) {
    await prisma.systemConfig.create({
      data: { key: "magic_word", value: "parangaricutirimirruaru" },
    });
    console.log('Palavra cabalística padrão criada!');
  } else {
    console.log('Palavra cabalística já existe. Pulando...');
  }

  console.log("Seed concluído!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
